# Generated by Django 5.2.1 on 2025-05-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0003_add_company_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='about_us',
            field=models.TextField(blank=True, verbose_name='О нас'),
        ),
        migrations.AddField(
            model_name='company',
            name='delivery_hours',
            field=models.CharField(blank=True, max_length=200, verbose_name='Часы доставки'),
        ),
        migrations.AddField(
            model_name='company',
            name='delivery_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость доставки'),
        ),
        migrations.AddField(
            model_name='company',
            name='delivery_time',
            field=models.CharField(blank=True, max_length=100, verbose_name='Время доставки'),
        ),
        migrations.AddField(
            model_name='company',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='company',
            name='free_delivery_from',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Бесплатная доставка от'),
        ),
        migrations.AddField(
            model_name='company',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='company',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='company',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='company',
            name='min_order_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Минимальная сумма заказа'),
        ),
        migrations.AddField(
            model_name='company',
            name='slogan',
            field=models.CharField(blank=True, max_length=200, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='company',
            name='vk',
            field=models.CharField(blank=True, max_length=100, verbose_name='VK'),
        ),
        migrations.AddField(
            model_name='company',
            name='working_hours',
            field=models.CharField(blank=True, max_length=200, verbose_name='Часы работы'),
        ),
    ]
