# Generated by Django 5.2.1 on 2025-05-29 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0010_add_initial_staff'),
        ('pizzeria', '0011_add_initial_staff'),
    ]

    operations = [
    ]
