# Generated by Django 5.2.1 on 2025-09-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0014_add_initial_articles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('number', models.CharField(max_length=100, verbose_name='Номер сертификата')),
                ('issue_date', models.DateField(verbose_name='Дата выдачи')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('issuing_authority', models.CharField(max_length=200, verbose_name='Кем выдан')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='certificates/', verbose_name='Изображение сертификата')),
                ('file', models.FileField(blank=True, null=True, upload_to='certificates/files/', verbose_name='Файл сертификата')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действующий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название компании')),
                ('description', models.TextField(verbose_name='Описание')),
                ('logo', models.ImageField(upload_to='partners/', verbose_name='Логотип')),
                ('website_url', models.URLField(verbose_name='Сайт компании')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
                'ordering': ['order', 'name'],
            },
        ),
    ]
